### ISSUE TITLE
Komunikat błędu: Wystąpił przynajmniej jeden błąd

### ISSUE THREAD

**Issue by kg1403** [soneta/Soneta.Platform.Developer#15]
Microsoft Visual Studio Enterprise 2019 Version 16.2.4
Podczas tworzenia projektu Soneta Addon Project pojawia się komunikat błędu.
![Komunikat błędu](https://user-images.githubusercontent.com/9596554/65577667-8ad62080-df74-11e9-9966-e4c178e69018.png)

**Comment by SebastianWabnik** [comment]
Zgodnie z instrukcją 
1. Jak chcemy założyć 3 warstowy projekt dodatku stosujemy Soneta Addon
2. Jak chcemy tylko logikę biznesową - najpierw zakładamy projekt konfiguracyjny Soneta Addon Config (który zawiera podstawowe elementy dla wykorzystania SDK) a dopiero potem dodajemy do solucji nowy projekt Soneta AddonProject
