### ISSUE TITLE
Utworzenie projektu Soneta Addon Project, Soneta Addon Project UI

### ISSUE THREAD

**Issue by RS2065** [soneta/Soneta.Platform.Developer#22]
Próba utworzenia projektów z poziomu Visual Studio nazwie

- Soneta Addon Project 
- Soneta Addon Project UI 

kończy się błędem:
**_One or more errors occured._**

Utworzenie pełnego projektu o nazwie Soneta Addon działa poprawnie jak również utworzenie Soneta Addon Config i dodanie opisanych na wstępie projektów zachowuje się prawidłowo.

**Comment by SebastianWabnik** [comment]
Trzeba uzupełnić dokumentacje 
Jak chcemy założyć 3 warstowy projekt dodatku stosujemy Soneta Addon
Jak chcemy tylko logikę biznesową - najpierw zakładamy projekt konfiguracyjny Soneta Addon Config (który zawiera podstawowe elementy dla wykorzystania SDK) a dopiero potem dodajemy do solucji nowy projekt Soneta AddonProject

**Comment by SebastianWabnik** [comment]
W najnowszych wersjach problem został usunięty
