### ISSUE TITLE
Brak wsparcia dla Visual Studio 2022

### ISSUE THREAD

**Issue by PawelHryniewiecki** [soneta/Soneta.Platform.Developer#26]
Witam,

Potrzebne wsparcie dla VS 2022.

**Comment by AndrzejRosada** [comment]
Zgadza się, potrzebne.

**Comment by PawelHryniewiecki** [comment]
> 

Na razie temat zgłosiłem przez pulpit partnera. Ponoć temat przekazany do produkcji...

**Comment by CICOMPUTER** [comment]
Zaczekamy więc na dalszy rozwój sprawy. Chociaż generalnie przez consolę to się instaluje - i wygląda, że działa. Gorzej natomiast z SonetaStudioExt.

**Comment by bartlomiejstrzebonski** [comment]
@SebastianWabnik czy w tym temacie coś będzie realizowane? Nie wiem jak u innych, ale u nas na VS2022 po instalacji SDK jest możliwość dodawania projektów w SDK (do wybrania z templatek), ale już plików wewnątrz projektowych nie (business.xml, pageform itp.)
Przy instalacji jest wyświetlana następująca informacja:

Error: Failed to read package information from NuGet source https://predica.pkgs.visualstudio.com/IT/_packaging/IT/nuget/v3/index.json.
Success: Soneta.Platform.Developer::1.0.3 installed the following templates:
Template Name                  Short Name               Language  Tags                            
-----------------------------  -----------------------  --------  --------------------------------
Soneta Addon                   soneta-addon             [C#]      Soneta/Addon                    
Soneta Addon Item BusinessXml  soneta-item-businessxml  [C#]      Soneta/Addon/Item/BusinessXml   
Soneta Addon Item Dashboard    soneta-item-dashboard    [C#]      Soneta/Addon/Item/Dashboard     
Soneta Addon Item PageForm     soneta-item-pageform     [C#]      Soneta/Addon/Item/PageForm      
Soneta Addon Item ViewInfo     soneta-item-viewinfo     [C#]      Soneta/Addon/Item/ViewInfo      
Soneta Addon Item Worker       soneta-item-worker       [C#]      Soneta/Addon/Item/Worker        
Soneta Addon Project           soneta-addon-project     [C#]      Soneta/Addon/Project            
Soneta Addon Project Config    soneta-addon-config      [C#]      Soneta/Addon/Config             
Soneta Addon Project Tests     soneta-addon-tests       [C#]      Soneta/Addon/Project/Tests/NUnit
Soneta Addon Project UI        soneta-addon-ui          [C#]      Soneta/Addon/Project/UI      

ale mimo to, nie ma możliwości dodania w projekcie soneta-items

**Comment by bartlomiejstrzebonski** [comment]
@SebastianWabnik  czy w tym temacie coś będzie realizowane? Nie wiem jak u innych, ale u nas na VS2022 po instalacji SDK jest możliwość dodawania projektów w SDK (do wybrania z templatek), ale już plików wewnątrz projektowych nie (business.xml, pageform itp.)
Przy instalacji jest wyświetlana następująca informacja:

Success: Soneta.Platform.Developer::1.0.3 installed the following templates:
Template Name Short Name Language Tags

Soneta Addon soneta-addon [C#] Soneta/Addon
Soneta Addon Item BusinessXml soneta-item-businessxml [C#] Soneta/Addon/Item/BusinessXml
Soneta Addon Item Dashboard soneta-item-dashboard [C#] Soneta/Addon/Item/Dashboard
Soneta Addon Item PageForm soneta-item-pageform [C#] Soneta/Addon/Item/PageForm
Soneta Addon Item ViewInfo soneta-item-viewinfo [C#] Soneta/Addon/Item/ViewInfo
Soneta Addon Item Worker soneta-item-worker [C#] Soneta/Addon/Item/Worker
Soneta Addon Project soneta-addon-project [C#] Soneta/Addon/Project
Soneta Addon Project Config soneta-addon-config [C#] Soneta/Addon/Config
Soneta Addon Project Tests soneta-addon-tests [C#] Soneta/Addon/Project/Tests/NUnit
Soneta Addon Project UI soneta-addon-ui [C#] Soneta/Addon/Project/UI

ale mimo to, nie ma możliwości dodania w projekcie soneta-items

**Comment by SebastianWabnik** [comment]
Hej,
Dziś albo jutro ogarnę ten temat - przepraszam za zwłokę.
Pozdrawiam,
Sebastian
________________________________
Od: Bartłomiej Strzeboński ***@***.***>
Wysłane: wtorek, 10 maja 2022 09:02:39
Do: soneta/Soneta.Platform.Developer
DW: Sebastian Wabnik; Mention
Temat: Re: [soneta/Soneta.Platform.Developer] Brak wsparcia dla Visual Studio 2022 (Issue #26)


@SebastianWabnik<https://github.com/SebastianWabnik> czy w tym temacie coś będzie realizowane? Nie wiem jak u innych, ale u nas na VS2022 po instalacji SDK jest możliwość dodawania projektów w SDK (do wybrania z templatek), ale już plików wewnątrz projektowych nie (business.xml, pageform itp.)
Przy instalacji jest wyświetlana następująca informacja:

Error: Failed to read package information from NuGet source https://predica.pkgs.visualstudio.com/IT/_packaging/IT/nuget/v3/index.json.
Success: Soneta.Platform.Developer::1.0.3 installed the following templates:
Template Name Short Name Language Tags

________________________________

Soneta Addon soneta-addon [C#] Soneta/Addon
Soneta Addon Item BusinessXml soneta-item-businessxml [C#] Soneta/Addon/Item/BusinessXml
Soneta Addon Item Dashboard soneta-item-dashboard [C#] Soneta/Addon/Item/Dashboard
Soneta Addon Item PageForm soneta-item-pageform [C#] Soneta/Addon/Item/PageForm
Soneta Addon Item ViewInfo soneta-item-viewinfo [C#] Soneta/Addon/Item/ViewInfo
Soneta Addon Item Worker soneta-item-worker [C#] Soneta/Addon/Item/Worker
Soneta Addon Project soneta-addon-project [C#] Soneta/Addon/Project
Soneta Addon Project Config soneta-addon-config [C#] Soneta/Addon/Config
Soneta Addon Project Tests soneta-addon-tests [C#] Soneta/Addon/Project/Tests/NUnit
Soneta Addon Project UI soneta-addon-ui [C#] Soneta/Addon/Project/UI

ale mimo to, nie ma możliwości dodania w projekcie soneta-items

**Comment by AndrzejRosada** [comment]
> @SebastianWabnik czy w tym temacie coś będzie realizowane? Nie wiem jak u innych, ale u nas na VS2022 po instalacji SDK jest możliwość dodawania projektów w SDK (do wybrania z templatek), ale już plików wewnątrz projektowych nie (business.xml, pageform itp.) Przy instalacji jest wyświetlana następująca informacja:
> 
> Success: Soneta.Platform.Developer::1.0.3 installed the following templates: Template Name Short Name Language Tags
> 
> Soneta Addon soneta-addon [C#] Soneta/Addon Soneta Addon Item BusinessXml soneta-item-businessxml [C#] Soneta/Addon/Item/BusinessXml Soneta Addon Item Dashboard soneta-item-dashboard [C#] Soneta/Addon/Item/Dashboard Soneta Addon Item PageForm soneta-item-pageform [C#] Soneta/Addon/Item/PageForm Soneta Addon Item ViewInfo soneta-item-viewinfo [C#] Soneta/Addon/Item/ViewInfo Soneta Addon Item Worker soneta-item-worker [C#] Soneta/Addon/Item/Worker Soneta Addon Project soneta-addon-project [C#] Soneta/Addon/Project Soneta Addon Project Config soneta-addon-config [C#] Soneta/Addon/Config Soneta Addon Project Tests soneta-addon-tests [C#] Soneta/Addon/Project/Tests/NUnit Soneta Addon Project UI soneta-addon-ui [C#] Soneta/Addon/Project/UI
> 
> ale mimo to, nie ma możliwości dodania w projekcie soneta-items

Tak, efekt chyba u wszystkich jest taki sam, brak items-ów.

**Comment by SebastianWabnik** [comment]
Czekam na review wydania 
https://github.com/soneta/Soneta.Platform.Developer/pull/28
