### ISSUE TITLE
Visual studio 2022 17.2.3 

### ISSUE THREAD

**Issue by DudaLuk** [soneta/Soneta.Platform.Developer#29]
na wersji 17.2.3 nie tworzą się projekty otwiera się pusta solucja 
![obraz](https://user-images.githubusercontent.com/89943288/171826407-74573897-e54c-4371-ae6d-a510cc4d9827.png)

**Comment by damdyn** [comment]
Dziękuję za zgłoszenie, problem jest nam zanany i pracujemy nad rozwiązaniem. Aktualizacja vs przyniosła zmiany, zrywające kompatybilność z naszym rozwiązaniem. Co jest ciekawe projekty zostały utworzone, ale mają niewłaściwą strukturę. Rozwiązaniem może być przeniesienie plików: **"Directory.Build.props**" oraz "**global.json**"  z katalogu "***.Config** "do katalogu, gdzie znajduje się solucja. Następnie usunąć cały katalog "***.Config**" oraz dodać projekty do solucji ręcznie.

**Comment by bartcho** [comment]
Jest jeszcze jedno rozwiązanie:
dotnet new --install Soneta.Platform.Developer

wtedy oprócz możliwości dodawania z cmdline poprzez dotnet new, templat'y są widoczne także w VS i działają dobrze

PS. Tylko uwaga, bo przy zainstalowaniu Soneta.Platform.Developer z makretplace i poprzez dotnet new --install Soneta.Platform.Developer w VS są dwa zestawy templatów i te dobrze działające to [NazwaTemplate'a] (Soneta)

**Comment by damdyn** [comment]
Tutaj do rozwiązania zaproponowanego przez @bartcho należy dodać, że aby to zadziałało z poziomu VS trzeba zaznaczyć:
![image](https://user-images.githubusercontent.com/33690517/177727416-f0c15bb4-edbc-417c-87e3-d2db8bd9210b.png)

**Comment by damdyn** [comment]
@DudaLuk  Powstał pr z próbą rozwiązania problemu. Proszę sprawdź czy już jest ok. Wystarczy zbudować rozwiązanie, odinstalować stary dodatek i zainstalować nowo zbudowany z tego pr #33

**Comment by DudaLuk** [comment]
@damdyn  Działa jak marzenie :)
