### ISSUE TITLE
An item with the same key already been added.

### ISSUE THREAD

**Issue by DudaLuk** [soneta/Soneta.Platform.Developer#35]
Podczas dodawania pageform/workera/itp elementu  do projektu pojawia się komunikat:
![image](https://user-images.githubusercontent.com/89943288/191471606-757a78d9-7f2b-4cfa-aec5-9f16515c897e.png)
Visual Studio 17.3.4 

![image](https://user-images.githubusercontent.com/89943288/191475090-9e75ef0c-477d-4e66-8056-024132075e45.png)

**Comment by SebastianWabnik** [comment]
Cześć,
Potwierdzam problem -rozpoczynam analizę.
