### ISSUE TITLE
Dostarczać do projektów aktualne pliki xsd w celu wsparcia intellisense

### ISSUE THREAD

**Issue by bartcho** [soneta/Soneta.Platform.Developer#6]
Co do sposobu najlepiej razem z nugetami.
Pytanie jak je optymalnie umiejscowić w projekcie, aby działały zarówno w VS i VSCode.

**Comment by SylwesterZarebski** [comment]
Niektóre biblioteki dają osobne paczki NuGet z nazewnictwem *.Schema (np. NLog.Schema).

W paczkach bazowych nie powinno być XSD, bo wtedy pojawi się problem przy użyciu paczek w wielu projektach w jednej solucji - może istnieć tylko jedna definicja XSD (w sensie dla tego samego typu) na całą solucję.

PS. Czy warto uwzględniać VSCode w tym równaniu, skoro VSCode natywnie nie obsługuje XSD, a tylko przy użyciu rozszerzeń, z których każde działa nieco inaczej?

**Comment by bartcho** [comment]
Temat wzięty na tapetę na ten sprint.
Będziemy informować jak planujemy to rozwiązać i z czego tak naprawdę wynikają problemy.
Dziękuję za zainteresowanie @SylwesterZarebski

**Comment by a4099181** [comment]
PR #17

**Comment by bartcho** [comment]
PR #20
